[tools]
python = "3.12"

[tasks.dev]
description = "Levantar el servidor FastAPI en modo desarrollo (Reload)"
run = "uv run uvicorn main:app --reload --host 127.0.0.1 --port 8000"

[tasks.start]
description = "Levantar el servidor FastAPI en modo producción"
run = "uv run uvicorn main:app --host 0.0.0.0 --port 8000"
