[tools]
python = "3.12"

[tasks.dev]
description = "Deploy the FastAPI server in deveploment mode (Reload)"
run = "uv run uvicorn main:app --app-dir src --reload --host 127.0.0.1 --port 8000"

[tasks.set-webhook]
description = "Set the webhook"
usage = '''
arg "<url>" help="The URL to which the bot will make requests"
'''

run = '''
curl -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/setWebhook" \
     -H "Content-Type: application/json" \
     -d "{\"url\": \"${usage_url?}/webhook/telegram/\"}"
'''

[tasks.prod]
description = "Deploy the FastAPI server in production mode"
run = "uv run uvicorn main:app --app-dir src --host 0.0.0.0 --port 8000"

[tasks.db-migrate]
description = "Apply database migrations"
run = "uv run python src/migrate.py"

[tasks.verify-webhook]
description = "Verify state of the webhook"
run = 'curl "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/getWebhookInfo"'
